accounts/urls.py
from django.urls import path

from .views.common_views import *
from accounts.views.quick_add_views import QuickAddPatientView, QuickAddDoctorView

app_name = "accounts"

urlpatterns = [
    path(
        "doctor/register/",
        RegisterDoctorView.as_view(),
        name="doctor-register",
    ),
    path(
        "patient/register/",
        RegisterPatientView.as_view(),
        name="patient-register",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("login/", LoginView.as_view(), name="login"),
    path(
        "update-basic-information/",
        UpdateBasicUserInformationAPIView.as_view(),
        name="update-basic-information",
    ),

    # Agregar estas URLs en el urlpatterns existente:
    path('quick-add-patient/', QuickAddPatientView.as_view(), name='quick-add-patient'),
    path('quick-add-doctor/', QuickAddDoctorView.as_view(), name='quick-add-doctor'),
]

core/urls.py
from django.urls import path
from .views import home, TermsView, PrivacyView

app_name = "core"

urlpatterns = [
    path("", home, name="home"),
    path("terms/", TermsView.as_view(), name="terms"),
    path("privacy/", PrivacyView.as_view(), name="privacy"),
]

doccure/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from accounts.views.admin_views import (
    AdminDashboardView,
    AdminPatientsView,
    AdminDoctorsView,
    AdminAppointmentsView,
    AdminSpecialitiesView,
    SpecialityCreateView,
    SpecialityUpdateView,
    SpecialityDeleteView,
    AdminPrescriptionsView,
    AdminReviewListView,
    AppointmentReportView,
    RevenueReportView,
)

admin.site.site_header = "Doccure Admin"
admin.site.site_title = "Doccure Admin Portal"
admin.site.index_title = "Welcome to Doccure Admin Portal"


urlpatterns = (
    [
        path("super-admin/", admin.site.urls),
        path("accounts/", include("accounts.urls")),
        path("patients/", include("patients.urls")),
        path("doctors/", include("doctors.urls")),
        path("bookings/", include("bookings.urls")),
        path("", include("core.urls")),
        path("__debug__/", include(debug_toolbar.urls)),
        path("ckeditor/", include("ckeditor_uploader.urls")),
        path(
            "admin/",
            include(
                [
                    path(
                        "",
                        AdminDashboardView.as_view(),
                        name="admin-dashboard",
                    ),
                    path(
                        "patients/",
                        AdminPatientsView.as_view(),
                        name="admin-patients",
                    ),
                    path(
                        "doctors/",
                        AdminDoctorsView.as_view(),
                        name="admin-doctors",
                    ),
                    path(
                        "appointments/",
                        AdminAppointmentsView.as_view(),
                        name="admin-appointments",
                    ),
                    path(
                        "specialities/",
                        AdminSpecialitiesView.as_view(),
                        name="admin-specialities",
                    ),
                    path(
                        "specialities/create/",
                        SpecialityCreateView.as_view(),
                        name="admin-speciality-create",
                    ),
                    path(
                        "specialities/<int:pk>/update/",
                        SpecialityUpdateView.as_view(),
                        name="admin-speciality-update",
                    ),
                    path(
                        "specialities/<int:pk>/delete/",
                        SpecialityDeleteView.as_view(),
                        name="admin-speciality-delete",
                    ),
                    path(
                        "prescriptions/",
                        AdminPrescriptionsView.as_view(),
                        name="admin-prescriptions",
                    ),
                    path(
                        "reviews/",
                        AdminReviewListView.as_view(),
                        name="admin-reviews",
                    ),
                    path(
                        "reports/appointments/",
                        AppointmentReportView.as_view(),
                        name="admin-appointment-report",
                    ),
                    path(
                        "reports/revenue/",
                        RevenueReportView.as_view(),
                        name="admin-revenue-report",
                    ),
                ],
            ),
            
        ),
        path('reports/', include('reports.urls')),
        path('feedback/', include('feedback.urls', namespace='feedback')),
        path("reminders/", include("reminders.urls")),
        path('security/', include('security.urls')),
        
        
        
        # path("super-admin/", admin.site.urls),
        # path("accounts/", include("accounts.urls")),
        # path("patients/", include("patients.urls")),
        # path("doctors/", include("doctors.urls")),
        # path("bookings/", include("bookings.urls")),
        # path("", include("core.urls")),
        # path("security/", include("security.urls")),  # Add this line
        # path("__debug__/", include(debug_toolbar.urls)),
    ]
    
        
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

security/audit/urls.py
from django.urls import path
from . import views

app_name = 'audit'

urlpatterns = [
    path('dashboard/', views.audit_dashboard, name='dashboard'),
    path('logs/', views.audit_logs, name='logs'),
    path('settings/', views.audit_settings, name='settings'),
]

security/permissions/urls.py
from django.urls import path
from . import views

app_name = 'permissions'

urlpatterns = [
    path('manage/', views.manage_permissions, name='manage'),
]

templates/dashboard/includes/admin-sidebar.html
{% load static %}

<!-- Sidebar -->
<div class="sidebar" id="sidebar">
    <div class="sidebar-inner slimscroll">
        <div id="sidebar-menu" class="sidebar-menu">
            <ul>
                <li class="menu-title">
                    <span>Main</span>
                </li>
                <li class="{% if request.resolver_match.url_name == 'admin-dashboard' %}active{% endif %}">
                    <a href="{% url 'accounts:admin-dashboard' %}"><i class="fe fe-home"></i> <span>Dashboard</span></a>
                </li>
                <li class="{% if 'appointment' in request.resolver_match.url_name %}active{% endif %}">
                    <a href="{% url 'accounts:admin-appointment-list' %}"><i class="fe fe-calendar"></i> <span>Appointments</span></a>
                </li>
                
                <li class="submenu {% if 'doctor' in request.resolver_match.url_name %}active{% endif %}">
                    <a href="#"><i class="fe fe-user-plus"></i> <span> Doctors</span> <span class="menu-arrow"></span></a>
                    <ul style="display: {% if 'doctor' in request.resolver_match.url_name %}block{% else %}none{% endif %};">
                        <li><a href="{% url 'accounts:admin-doctor-list' %}">Doctor List</a></li>
                    </ul>
                </li>
                
                <li class="submenu {% if 'patient' in request.resolver_match.url_name %}active{% endif %}">
                    <a href="#"><i class="fe fe-user"></i> <span> Patients</span> <span class="menu-arrow"></span></a>
                    <ul style="display: {% if 'patient' in request.resolver_match.url_name %}block{% else %}none{% endif %};">
                        <li><a href="{% url 'accounts:admin-patient-list' %}">Patient List</a></li>
                    </ul>
                </li>
                
                <li class="submenu {% if 'speciality' in request.resolver_match.url_name %}active{% endif %}">
                    <a href="#"><i class="fe fe-users"></i> <span> Specialities</span> <span class="menu-arrow"></span></a>
                    <ul style="display: {% if 'speciality' in request.resolver_match.url_name %}block{% else %}none{% endif %};">
                        <li><a href="{% url 'accounts:admin-speciality-list' %}">Speciality List</a></li>
                    </ul>
                </li>

                <!-- Informes y Análisis -->
                {% if user.is_authenticated %}
                <li class="submenu {% if 'reports' in request.path %}active{% endif %}">
                    <a href="#"><i class="fe fe-bar-chart"></i> <span>Informes y Análisis</span> <span class="menu-arrow"></span></a>
                    <ul style="display: {% if 'reports' in request.path %}block{% else %}none{% endif %};">
                        <li><a href="{% url 'reports-dashboard' %}">Dashboard</a></li>
                        <li><a href="{% url 'appointment-report' %}">Informe de Citas</a></li>
                        <li><a href="{% url 'revenue-report' %}">Informe de Ingresos</a></li>
                        {% if user.is_staff %}
                        <li><a href="{% url 'doctor-performance-report' %}">Rendimiento de Médicos</a></li>
                        <li><a href="{% url 'specialty-analysis' %}">Análisis de Especialidades</a></li>
                        {% endif %}
                    </ul>
                </li>
                {% endif %}
                

                
                <li>
                    <a href="{% url 'accounts:logout' %}"><i class="fe fe-logout"></i> <span>Logout</span></a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- /Sidebar -->

templates/dashboard/includes/header.html
{% load static %}

<!-- Header -->
<div class="header">

    <!-- Logo -->
    <div class="header-left">
        <a href="{% url 'admin-dashboard' %}" class="logo d-block">
            <img src="{% static 'dashboard/assets/img/logo2.svg' %}" alt="Logo">
        </a>
        <a href="{% url 'admin-dashboard' %}" class="logo logo-small d-block">
            <img src="{% static 'dashboard/assets/img/logo-small.png' %}" alt="Logo" width="30" height="30">
        </a>
    </div>
    <!-- /Logo -->
    
    <a href="javascript:void(0);" id="toggle_btn">
        <i class="fe fe-text-align-left"></i>
    </a>
    
    <div class="top-nav-search">
        <form>
            <input type="text" class="form-control" placeholder="Search here">
            <button class="btn" type="submit"><i class="fa fa-search"></i></button>
        </form>
    </div>
    
    <!-- Mobile Menu Toggle -->
    <a class="mobile_btn" id="mobile_btn">
        <i class="fa fa-bars"></i>
    </a>
    <!-- /Mobile Menu Toggle -->
    
    <!-- Header Right Menu -->
    <ul class="nav user-menu">

        <!-- User Menu -->
        <li class="nav-item dropdown has-arrow">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                <span class="user-img">
                    <img class="rounded-circle" src="{{ user.profile.image }}" width="31" alt="Admin">
                </span>
            </a>
            <div class="dropdown-menu">
                <div class="user-header">
                    <div class="avatar avatar-sm">
                        <img src="{{ user.profile.image }}" alt="User Image" class="avatar-img rounded-circle">
                    </div>
                    <div class="user-text">
                        <h6>{{ user.get_full_name }}</h6>
                        <p class="text-muted mb-0">Administrator</p>
                    </div>
                </div>
                {% comment %} <a class="dropdown-item" href="{% url 'admin-profile' %}">My Profile</a> {% endcomment %}
                {% comment %} <a class="dropdown-item" href="{% url 'admin-settings' %}">Settings</a> {% endcomment %}
                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
            </div>
        </li>
        <!-- /User Menu -->
        
    </ul>
    <!-- /Header Right Menu -->
    
</div>
<!-- /Header -->

templates/dashboard/includes/sidebar.html
<!-- Sidebar -->
<div class="sidebar" id="sidebar">
    <div class="sidebar-inner slimscroll">
        <div id="sidebar-menu" class="sidebar-menu">
            <ul>
                <li class="menu-title"> 
                    <span>Main</span>
                </li>
                <li {% if request.path == '/admin/' %}class="active"{% endif %}> 
                    <a href="{% url 'admin-dashboard' %}"><i class="fe fe-home"></i> <span>Dashboard</span></a>
                </li>
                <li {% if request.path == '/admin/appointments/' %}class="active"{% endif %}> 
                    <a href="{% url 'admin-appointments' %}"><i class="fe fe-layout"></i> <span>Appointments</span></a>
                </li>
                <li {% if request.path == '/admin/specialities/' %}class="active"{% endif %}> 
                    <a href="{% url 'admin-specialities' %}"><i class="fe fe-users"></i> <span>Specialities</span></a>
                </li>
                <li {% if request.path == '/admin/doctors/' %}class="active"{% endif %}> 
                    <a href="{% url 'admin-doctors' %}"><i class="fe fe-user-plus"></i> <span>Doctors</span></a>
                </li>
                <li {% if request.path == '/admin/patients/' %}class="active"{% endif %}> 
                    <a href="{% url 'admin-patients' %}"><i class="fe fe-user"></i> <span>Patients</span></a>
                </li>
                <li {% if request.path == '/admin/prescriptions/' %}class="active"{% endif %}> 
                    <a href="{% url 'admin-prescriptions' %}"><i class="fe fe-file"></i> <span>Prescriptions</span></a>
                </li>
                <li {% if request.path == '/admin/reviews/' %}class="active"{% endif %}> 
                    <a href="{% url 'admin-reviews' %}"><i class="fe fe-star-o"></i> <span>Reviews</span></a>
                </li>
                <li> 
                    <a href=""><i class="fe fe-activity"></i> <span>Transactions</span></a>
                </li>
                <li class="submenu">
                    <a href="#"><i class="fe fe-document"></i> <span> Reports</span> <span class="menu-arrow"></span></a>
                    <ul style="display: none;">
                        <li {% if request.path == '/admin/reports/appointments/' %}class="active"{% endif %}><a href="{% url 'admin-appointment-report' %}">Appointment Reports</a></li>
                        <li {% if request.path == '/admin/reports/revenue/' %}class="active"{% endif %}><a href="{% url 'admin-revenue-report' %}">Revenue Reports</a></li>
                    </ul>
                </li>
                <!-- Nuevo enlace para gestión de permisos -->
                <li {% if '/security/permissions/manage/' in request.path %}class="active"{% endif %}> 
                    <a href="{% url 'permissions:manage' %}"><i class="fe fe-shield"></i> <span>Gestión de Permisos</span></a>
                </li>
                <li {% if '/security/audit/' in request.path %}class="active"{% endif %}> 
                    <a href="{% url 'audit:dashboard' %}"><i class="fe fe-activity"></i> <span>Auditoría del Sistema</span></a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- /Sidebar -->